# Generated by Django 4.2.13 on 2024-06-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hosp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_id', models.CharField(max_length=200)),
                ('hospitalName', models.CharField(max_length=200)),
                ('hospitalAddr', models.CharField(max_length=200)),
                ('otherInfo', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('mobileNo', models.CharField(max_length=200)),
            ],
        ),
    ]
