# Generated by Django 4.2.13 on 2024-06-28 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cruds', '0003_crud_diag_crud_rmrks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crud',
            name='diag',
        ),
        migrations.RemoveField(
            model_name='crud',
            name='rmrks',
        ),
    ]
