# Generated by Django 4.2.13 on 2024-06-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruds', '0004_remove_crud_diag_remove_crud_rmrks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admID', models.CharField(max_length=200)),
                ('phNo', models.CharField(max_length=200)),
                ('hosp_id', models.CharField(max_length=200)),
                ('admDate', models.DateField()),
                ('discDate', models.DateField()),
                ('diag', models.CharField(max_length=200)),
                ('rmrks', models.CharField(max_length=200)),
            ],
        ),
    ]
