# Generated by Django 4.2.13 on 2024-06-28 07:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cruds', '0005_admission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='admID',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=200, unique=True),
        ),
    ]
