# Generated by Django 5.0.6 on 2024-06-29 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cruds", "0006_alter_admission_admid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hosp",
            name="id",
        ),
        migrations.AlterField(
            model_name="hosp",
            name="hospital_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
